# Generated by Django 2.2.3 on 2019-07-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_email', models.EmailField(max_length=254, null=True)),
                ('modal_password', models.CharField(max_length=50, null=True)),
                ('modal_image', models.ImageField(null=True, upload_to='modal-image')),
                ('minimal', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('California', 'California'), ('Delawar', 'Delawar'), ('Texas', 'Texas'), ('New York', 'New York')], default=None, max_length=10)),
                ('multiple', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('California', 'California'), ('Delawar', 'Delawar'), ('Texas', 'Texas'), ('New York', 'New York')], default=None, max_length=10)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
